[package]
name = "capeos-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "capeos-cli"
path = "src/main.rs"

[dependencies]
capeos-common = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
